auto: false
url: http://jivoi.github.io
permalink: /:year/:month/:day/:title.html
pygments: true

author: Jivoi
author_link: http://jivoi.github.io

exclude: ['Rakefile', 'README.markdown', 'README.textile', '_design']
