auto: false
url: http://yajivoi.com
permalink: /:year/:month/:day/:title.html
pygments: true

author: Jivoi
author_link: http://yajivoi.com

exclude: ['Rakefile', 'README.markdown', 'README.textile', '_design']
